# Generated by Django 2.2 on 2020-03-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
