# Generated by Django 2.2 on 2020-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200316_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
