# Generated by Django 2.2 on 2020-03-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200316_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(choices=[('GR1', 'Grade 1'), ('GR2', 'Grade 2'), ('GR3', 'Grade 3')], default='GR1', max_length=30),
        ),
    ]
