# Generated by Django 2.2 on 2020-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200316_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(choices=[('GR1', 'GR1'), ('GR2', 'GR2'), ('GR3', 'GR3')], max_length=30),
        ),
    ]
