# Generated by Django 2.2 on 2020-03-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
