# Generated by Django 2.2 on 2020-03-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_user_phone'),
        ('main', '0020_parent_phone'),
    ]

    operations = [
    ]
