# Generated by Django 2.2 on 2020-03-26 12:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200326_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+639175126253', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
