# Generated by Django 2.2 on 2020-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(choices=[('K', 'K'), ('GR1', 'GR1'), ('GR2', 'GR2'), ('GR3', 'GR3'), ('GR4', 'GR4'), ('GR5', 'GR5'), ('GR6', 'GR6'), ('GR7', 'GR7'), ('GR8', 'GR8'), ('GR9', 'GR9'), ('GR10', 'GR10'), ('GR11', 'GR11'), ('GR12', 'GR12')], max_length=30),
        ),
    ]
