# Generated by Django 2.2 on 2020-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200326_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=2000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
