# Generated by Django 2.2 on 2020-03-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_message',
            name='date',
        ),
    ]
