# Generated by Django 2.2 on 2020-03-28 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200329_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 0, 46, 13, 722892)),
        ),
    ]
