# Generated by Django 2.2 on 2020-04-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200401_2213'),
        ('main', '0029_auto_20200330_1843'),
    ]

    operations = [
    ]
