# Generated by Django 2.2 on 2020-04-01 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_merge_20200402_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 0, 33, 53, 951662)),
        ),
    ]
