# Generated by Django 2.2 on 2020-04-01 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200402_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 2, 17, 41, 818238)),
        ),
    ]
