# Generated by Django 2.2 on 2020-04-03 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200402_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 15, 19, 30, 795216)),
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('K', 'K'), ('GR1', 'GR1'), ('GR2', 'GR2'), ('GR3', 'GR3'), ('GR4', 'GR4'), ('GR5', 'GR5'), ('GR6', 'GR6'), ('GR7', 'GR7'), ('GR8', 'GR8'), ('GR9', 'GR9'), ('GR10', 'GR10'), ('GR11', 'GR11'), ('GR12', 'GR12')], max_length=30)),
                ('section', models.ManyToManyField(to='main.Section')),
            ],
        ),
    ]
