# Generated by Django 2.2 on 2020-04-03 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200403_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 21, 57, 11, 931826)),
        ),
    ]
